name: krx.io
description: "Ideas and thoughts"
url: "http://krx.io"
markdown: kramdown
highlighter: rouge
markdown_ext:  markdown,mkd,mkdn,md
permalink: /blog/:year/:month/:day/:title
paginate: 9
paginate_path: "blog/page/:num"

exclude: ['scripts','scss', 'README.md', 'CNAME', 'Gemfile', 'Gemfile.lock', '.ruby-version']

redcarpet:
  extensions: ['no_intra_emphasis',
               'fenced_code_blocks',
               'strikethrough',
               'superscript',
               'autolink',
               'with_toc_data',
               'tables']
sass:
  style: :compressed
gems:
  - jemoji
  - jekyll-mentions
