name: krx.io
description: "Ideas and thoughts"
url: "http://krx.io"
pygments: true
markdown: redcarpet
markdown_ext:  markdown,mkd,mkdn,md
permalink: /blog/:year/:month/:day/:title

redcarpet:
  extensions: ['no_intra_emphasis',
               'fenced_code_blocks',
               'strikethrough',
               'superscript',
               'autolink',
               'with_toc_data',
               'tables']
