name: krx.io
description: "Ideas and thoughts"
url: "http://krx.io"
markdown: kramdown
highlighter: rouge
markdown_ext:  markdown,mkd,mkdn,md
permalink: /blog/:year/:month/:day/:title
paginate: 9
paginate_path: "blog/page/:num"

exclude: ['scripts','scss', 'README.md', 'CNAME', 'Gemfile', 'Gemfile.lock', '.ruby-version']

kramdown:
  input: GFM
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  enable_coderay: false

sass:
  style: :compressed
gems:
  - jemoji
  - jekyll-mentions
  - jekyll-paginate
