title: krx.io
author:
  name: Kristian Rasmussen
  email: me@krx.io
description: > # this means to ignore newlines until "show_excerpts:"
  This should contain some nice description of what this is all about.
  Can't say that I'm entirely sure, except fun, code and thoughts from me.

show_excerpts: false # set to true to show excerpts on the homepage

# Minima date format
# refer to https://shopify.github.io/liquid/filters/date/ if you want to customize this
minima:
  date_format: "%b %-d, %Y"
  skin: solarized

  # generate social links in footer
  social_links:
    - { platform: github,         user_url: "https://github.com/iamkristian" }
    - { platform: instagram,      user_url: "https://www.instagram.com/iamkristian" }
    - { platform: linkedin,       user_url: "https://www.linkedin.com/in/iamkristian" }
    - { platform: youtube,        user_url: "https://www.youtube.com/jekyll" }
    - { platform: rss,            user_url: "https://iamkristian.github.io/feed.xml" }

# If you want to link only specific pages in your header, uncomment
# this and add the path to the pages in order as they should show up
#header_pages:
# - about.md

# Build settings
theme: minima

plugins:
 - jekyll-feed

markdown: kramdown
highlighter: rouge
#permalink: /blog/:year/:month/:day/:title
#paginate: 9
#paginate_path: "/blog/page:num"

pagination:
  enabled: true
  collection: 'posts'
  per_page: 6
  permalink: '/page/:num/'
  title: ':title - page :num of :max'
  limit: 0
  sort_field: 'date'
  sort_reverse: true

header_pages:
  - blog/index.md
  - about/index.md

kramdown:
  input: GFM
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  syntax_highlighter: rouge
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  enable_coderay: false
